### PR TITLE
Update mpileup differences caused by randomized overlap removal

### PR DESCRIPTION
**Pull request by pd3**
see https://github.com/samtools/htslib/pull/1273

### CODE REVIEW

**Comment by valeriuo** [comment]
Merged into develop as 388de5a336925f4fa4d60861fa50db6253f40545

**Comment by valeriuo** [comment]
Reverting develop to 38139f73c89f0aac6a920635036cb914aab342a2 and reopening this PR, as there are still some failed tests.

**Comment by daviesrob** [comment]
I think ideally you should include commit 388de5a336925f4fa4d60861fa50db6253f40545, just in case anyone cloned it while it was at the tip of develop (just rebase b29a045 on to it).

**Comment by valeriuo** [comment]
Both commits are in this PR and both will be merged into develop.

**Comment by daviesrob** [comment]
Good, thanks.

**Pull request merged**
