### PR TITLE
Fixes #450

### LINKED ISSUE #450: Fallout from the output-fmt-options merge
PR #395 has been merged, but there are a few aspects of the additions that need further tidying up:

- The following don't use global options, though at least some probably should:
  - [ ] bam_cat.c
  - [ ] bam_index.c
  - [ ] bam_md.c
  - [ ] bam_rmdup.c
  - [ ] padding.c
- Need to integrate existing `ref.fasta` arguments or `-f`/etc options with the new `--reference` in
  - [ ] bam_md.c (once it uses global options!)
  - [ ] bam_plcmd.c
  - [ ] bam_tview.c
  - [ ] cut_target.c
  - [ ] sam_view.c
- [ ] Need to resurrect `sam_open_mode()` or an equivalent in bam_mate.c and bam_sort.c

### PR DESCRIPTION
**Pull request by jkbonfield**
At least partially.

Added global I/O options to calmd (mostly pointless), depad (now also in the standard list of sub-commands) and rmdup.  Rmdup now actually "works" too due to  finally implementing bam_get_library().

Made the --reference and other options mostly do the same thing.  Mpileup still treats these differently (as it changes the output), while some other tools process them as a separate argument permitting them to both be specified and differ, but accepting --reference as a default for the reference option.  The reason is that --reference MUST much the reference used when encoding a cram, but we may wish to use a subtly different reference for the actual tool (SNP comparison, etc).

Samtools cat and index are unchanged as they operate on low level file blocks and so the global options are inappropriate.

NOTE: I haven't yet done anything with sam_open_mode().

### CODE REVIEW

**Comment by jkbonfield** [comment]
Oops, forgot that. I'll work on it.

**Comment by jmarshall** [comment]
We could of course consider that in future, but we are most certainly not going to devote any brain cycles whatsoever to it before the upcoming release!

**Comment by jkbonfield** [comment]
Gah, noticed rmdup still not working quite right.  Hold off on this PR for now.
I had incoming code for sam_open_mode() too.

**Comment by jkbonfield** [comment]
I believe I've now caught all the places we needed to add sam_open_mode(), fixing some rather broken regressions. Oops.  Also fixed rmdup so it actually used getopt_long.  It's been a long day.

TODO: our test harness really needs to be able to check the file formats and to repeat all commands in all formats.

Anyway, I'm happy with this PR now.  The only change I may wish to make is samtools view -o to auto-detect.  I didn't add it as it didn't previously do that either, but it's a bit of an outlier compared to other tools so perhaps this should be brought into line.

**Pull request merged**
