### PR TITLE
Add consensus to the samtools.1 man page.

### PR DESCRIPTION
**Pull request by jkbonfield**
Also fix a few minor problems in the samtoiols-consensus man page itself.

### CODE REVIEW

**Comment by babarlelephant** [comment]
Hi I'm having a hard time understanding the effect of min-depth, call-fract,  commands with -m bayesian

It is confusing because with -m simple it fits mostly my naive script parsing the .sam

**Comment by jkbonfield** [comment]
As per the command line usage, they have no impact on the Bayesian mode.

```
For simple consensus mode:
  -q, --(no-)use-qual   Use quality values in calculation [off]
  -c, --call-fract INT  At least INT portion of bases must agree [0.75]
  -d, --min-depth INT   Minimum depth of INT [1]
  -H, --het-fract INT   Minimum fraction of 2nd-most to most common base [0.5]

For default "Bayesian" consensus mode:
  -C, --cutoff C        Consensus cutoff quality C [10]
   ...
```

The man page is more explicit "The  following  options  apply  only  to the simple (default) consensus mode:"

Although I note that it wrongly claims the simple mode is the default.  We changed this to the more accurate Bayesian method late in development but apparently didn't spot this line in the man page.

**Comment by babarlelephant** [comment]
What is the unit of min-depth? I can retry but it seems to me that the unit is the number of reads in simple and something unclear in bayesian

**Comment by jkbonfield** [comment]
Sorry if this still isn't clear.  It *does nothing* in Bayesian mode, so the unit is irrelevant.  (But yes you're correct in simple mode "depth" is a couting bases)

The Bayesian method is purely working on probabilities and doesn't make use of heuristics such as depth or fractions/ratios of call vs SNPs.

**Comment by babarlelephant** [comment]
Thank you! This should explain the behavior :-)

**Pull request merged**
