### PR TITLE
Add linux gcc-8 case to Travis CI.

### PR DESCRIPTION
**Pull request by junaruga**
This pull-request is related to https://github.com/samtools/samtools/issues/951 .

In my repository, I tested it. Here is the result.
You can check how it looks like.
https://travis-ci.org/junaruga/samtools/builds/429213754

### CODE REVIEW

**Comment by daviesrob** [comment]
Thanks for the pull request.  Generally I think this is a good idea, although I do have a few observations:

- We should upgrade [htslib's Travis configuration ](https://github.com/samtools/htslib/blob/develop/.travis.yml) to try gcc-8 as well.  We don't want to rely on samtools to test parts of HTSlib.
- We might want to make gcc-8 the default and have the older compiler as the special case (if we bother with it at all).  Gcc-8 spots more problems than gcc-4, so it would be a better first choice.
- We don't want to run too many tests, so Travis finishes in a reasonable time.  This is more of an issue for HTSlib as it runs more cases.
- Samtools and HTSlib do get tested against gcc-8, albeit on Windows, by Appveyor.  I've also been using gcc 8.1 for a while, so there shouldn't be many gcc-8 related problems left by now.

**Comment by junaruga** [comment]
@daviesrob thanks for the observations. I basically agree for that.

> We should upgrade htslib's Travis configuration to try gcc-8 as well. We don't want to rely on samtools to test parts of HTSlib.

Yes, we need to update `htslib`'s configuration too. Actually that was my next plan after `samtools`.
So, after `samtools`, I can send pull-request to `htslibs` as well.

> We might want to make gcc-8 the default and have the older compiler as the special case (if we bother with it at all). Gcc-8 spots more problems than gcc-4, so it would be a better first choice.

I can agree with it.

Current test cases are

```
1. linux & clang
2. linux & gcc-4.8
3. linux & gcc-4.8 with "C99 and -O0"
4. osx & clang
```
And below test cases are your preference as a first choice right?
The case `osx & gcc-8` can be included as next choice?

```
1. linux & clang
2. linux & gcc-8
3. linux & gcc-8 with "C99 and -O0"
4. osx & clang
```

> We don't want to run too many tests, so Travis finishes in a reasonable time. This is more of an issue for HTSlib as it runs more cases.

Alright. That makes sense.

> Samtools and HTSlib do get tested against gcc-8, albeit on Windows, by Appveyor. I've also been using gcc 8.1 for a while, so there shouldn't be many gcc-8 related problems left by now.

That makes sense. But as I am not familiar with Windows and Appveyor, I would like to ask someone for the work.

Maybe I will update this PR tonight or tomorrow.

**Comment by junaruga** [comment]
I rebased with below way!

```
1. linux & clang
2. linux & gcc-8
3. linux & gcc-8 with "C99 and -O0"
4. osx & clang
```

**Comment by junaruga** [comment]
@daviesrob ping.

**Comment by daviesrob** [comment]
Sorry for the delay, this has been waiting on a companion in htslib (see samtools/htslib#781)

**Comment by junaruga** [comment]
@daviesrob alright! Thanks for the working of `htslib`.

**Comment by junaruga** [comment]
`htslib` with `gcc-8` is merged! Now it's time to merge for this PR.

**Comment by valeriuo** [comment]
Merged

**Pull request closed without merging**
