### PR TITLE
Initial draft of base modifications in mpileup.

### PR DESCRIPTION
**Pull request by jkbonfield**
These are enabled with -M or --output-mods.  This adds them to any
sequence bases (both matching ref and insertions).  This can make
parsing more complex, especially insertions, so --no-output-ins-mods
can be used to turn them off there.

Also extended mpileup to provide further control of output format via
--no-output-ins and --no-output-del, which may be used to make parsing
the sequence easier for specific applications that do not wish to
handle indels.

They both have two levels, to change from eg CCC-3NNNGCC to CCC-3GCC
to CCCGCC.  This will greatly simplify scripts that are simply trying
to count bases.

Similarly --no-output-ends removes the ^MQUAL and $ markup, which are
pretty unreliable frankly as they don't always appear on range
requests, when soft-clips are present, or when bases have been
quality filtered via -Q.

### CODE REVIEW

**Comment by jkbonfield** [comment]
Example output (possibly inappropriate as I've no idea if this sample should have base mods, but here it is anyway):

```
r3      29591   N       180     AAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAaaaaaaaAAAAAAAAAAAAAAAaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaAaAAAAAAaaAAAaaA    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!
r3      29592   N       180     C[+m21]C[+m24]C[+m18]C[+m25]C[+m28]C[+m18]C[+m18]C[+m41]C[+m31]C[+m20]C[+m18]C[+m18]C[+m18]C[+m21]ccccccccccccccccccccccccccccccccccccccccccccccccccccccC[+m19]C[+m18]C[+m18]C[+m18]C[+m18]C[+m18]C[+m19]cccccccC[+m18]C[+m18]C[+m18]C[+m18]C[+m18]C[+m22]C[+m30]C[+m18]C[+m22]C[+m20]C[+m18]C[+m22]C[+m18]C[+m19]C[+m19]ccccC[+m18]C[+m45]C[+m20]C[+m21]C[+m20]C[+m20]C[+m19]C[+m21]C[+m19]C[+m18]C[+m18]C[+m19]C[+m20]C[+m20]C[+m18]C[+m18]C[+m18]C[+m18]C[+m18]C[+m18]C[+m18]C[+m42]C[+m20]C[+m20]C[+m20]C[+m18]C[+m18]C[+m20]C[+m19]C[+m18]C[+m18]C[+m18]C[+m24]C[+m18]C[+m26]C[+m21]C[+m34]C[+m19]C[+m18]C[+m20]C[+m18]C[+m20]cccccccccccccccccccccC[+m18]cC[+m18]C[+m22]C[+m18]C[+m25]C[+m18]C[+m18]ccC[+m20]C[+m20]C[+m35]ccC[+m19]      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
r3      29593   N       180     GGGGGGGGGGGGGGg[+m18]g[+m20]g[+m20]g[+m58]g[+m18]g[+m18]g[+m18]g[+m23]g[+m18]g[+m21]g[+m18]g[+m20]g[+m18]g[+m79]g[+m18]g[+m32]g[+m19]g[+m55]g[+m18]g[+m22]g[+m36]g[+m18]g[+m19]g[+m46]g[+m20]g[+m21]g[+m18]g[+m18]g[+m20]g[+m18]g[+m45]g[+m26]g[+m21]g[+m30]g[+m18]g[+m18]g[+m22]g[+m22]g[+m28]g[+m18]g[+m66]g[+m18]g[+m24]g[+m19]g[+m237]g[+m19]g[+m23]g[+m25]g[+m18]g[+m18]g[+m24]g[+m43]g[+m21]g[+m24]GGGGGGGg[+m18]g[+m19]g[+m32]g[+m18]g[+m26]g[+m18]g[+m37]GGGGGGGGGGGGGGGg[+m20]g[+m22]g[+m18]g[+m22]GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGg[+m18]g[+m20]g[+m18]g[+m18]g[+m18]g[+m27]g[+m18]g[+m29]g[+m22]g[+m24]g[+m21]g[+m102]g[+m22]g[+m20]g[+m18]g[+m18]g[+m18]g[+m18]g[+m21]g[+m19]g[+m28]Gg[+m28]GGGGGGg[+m26]g[+m23]GGGg[+m18]g[+m36]G        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
r3      29594   N       180     AAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAaaaaaaaAAAAAAAAAAAAAAAaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaAaAAAAAAaaAAAaaA   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by jkbonfield** [comment]
Also partially addresses some of the issues mentioned in https://github.com/samtools/samtools/issues/1305

**Comment by jkbonfield** [comment]
NB checks fail due to not checking out the same branch in htslib.  We probably need to tweak the CI as we did (partially) with Travis.

**Comment by a-slide** [comment]
Awesome. Thank you for merging this MR.

**Comment by a-slide** [comment]
Any idea if this feature will be available in the next release of HTSlib + pileup in Samtools ?
If so, do you have an estimated date ?

**Comment by jkbonfield** [comment]
Yes to the first - it's merged now so will be in the next release.  As to the date, I can't really say, sorry.

**Pull request merged**
