### PR TITLE
Allow '*' for -T to write all tags to fastq

### PR DESCRIPTION
**Pull request by cjw85**
The command `samtools import` allows `-T "*"` to read all aux data from fastq headers. This PR makes `samtools fastq` symmetric by allowing all tags from SAM records to be written to fastq headers.

The motivation for this was for use with minimap2 to align reads with modified base data stored in unaligned SAM files (and not burden the user with knowing all tags).

### CODE REVIEW

**Comment by cjw85** [comment]
@jkbonfield I presume the rockylinux test is failing here only because things are running from my fork?

**Comment by cjw85** [comment]
Ooh, I think I noticed that `-T ''` would have the effect but forgot about it.

I'm on vacation at the moment, feel free to tidy this up.

**Comment by daviesrob** [comment]
Ok, I'll make the necessary adjustments.

**Comment by daviesrob** [comment]
Adjustments made.  Apologies for the forced push.

**Pull request merged**
