### PR TITLE
Adds `samtools quickcheck` subcommand

### PR DESCRIPTION
**Pull request by jrandall**
`samtools quickcheck` opens a set of SAM/BAM/CRAM files and
checks that the header of each contains at least one target
sequence, then (currently for BAM files only due to htslib
API limitations) seeks to the end of the file to check
whether the EOF block is intact.

Exits with a zero status if all input files checked out ok,
or a non-zero status otherwise. Can be made to give a list
of failing files (on stdout) using the `-v` option or to be
more verbose (on stderr) by giving additional `v` options.

### CODE REVIEW

**Comment by SamStudio8** [comment]
LGTM
> Reviewed-by: Sam Nicholls <sn8@sanger.ac.uk>

**Comment by jmarshall** [comment]
Samtools coding convention is for 4-position indentation done with spaces, not tabs.  bam_quickcheck.c contains a mixture of 4- and 2-position indenting and some of the lines use tabs to do so.  Please resubmit with the whitespace fixed up :smile_cat:

**Comment by jmarshall** [comment]
Otherwise, I'm happy to add the rest of the dependencies to the makefile and add tests to test.pl while merging.

**Comment by SamStudio8** [comment]
Retabbed in https://github.com/wtsi-hgi/samtools/pull/5

**Comment by SamStudio8** [comment]
Thanks @mp15

**Comment by SamStudio8** [comment]
Test failure unrelated to PR:
```
	268: Big SAM -> CRAM (2 threads)                            Assertion failed: (sym->x_max != 0), function RansEncPutSymbol, file ./cram/rANS_byte.h, line 271.
	Failed command:
	/Users/travis/build/samtools/samtools/samtools view -o /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/9Q24XGPi4t/view.test268.cram -C -@ 2 /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/9Q24XGPi4t/view.big.sam.gz
.. failed ...
	269: Big SAM -> CRAM (4 threads)                            	Failed command:
	/Users/travis/build/samtools/samtools/samtools view -o /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/9Q24XGPi4t/view.test269.cram -C -@ 4 /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/9Q24XGPi4t/view.big.sam.gz
.. failed ...
```

**Comment by SamStudio8** [comment]
@jmarshall Are you appeased? :smile_cat:

**Comment by jmarshall** [comment]
(The unrelated test failure is PR samtools/htslib#253.)

The indentation now passes muster, thanks.

Please squash; ideally fix up the trailing spaces in bam_quickcheck.c and the samtools.1 additions; and reverse the `usage_quickcheck` invocations.  The `default` one is due to invalid options so should be to stderr, while the `argc < 1` one is effectively `--help` so should be to stdout.

**Comment by SamStudio8** [comment]
@jmarshall Sorry missed those spaces. Your comments have been addressed in https://github.com/wtsi-hgi/samtools/pull/6. @mp15 can you squash these for me as per John's request? I don't have write access to the wtsi-hgi/samtools branch.

**Comment by jmarshall** [comment]
Thanks Sam!

**Comment by mp15** [comment]
Squashed into a patch and rebased to current develop for merge.

**Pull request merged**
