### PR TITLE
Update copyright dates to 2020 where needed.

### PR DESCRIPTION
**Pull request by whitwham**
In preparation for the next release, update all copyright dates for files that have been altered.

### CODE REVIEW

**Comment by whitwham** [comment]
I'll keep this PR updated until we are ready to release.

**Comment by whitwham** [comment]
Some are these are just whitespace or updated copyright notices.  I should probably weed some of those out.

**Comment by whitwham** [comment]
Second attempt.  This should have excluded most of the minor changes.

**Comment by jmarshall** [comment]
Not to be forgotten: year bumps in _LICENSE_ and `samtools --version`, cf 18be38a15d2c414fc2c260c27e5472149f35862d et al.

**Comment by whitwham** [comment]
> 
> 
> Not to be forgotten: year bumps in _LICENSE_ and `samtools --version`, cf [18be38a](https://github.com/samtools/samtools/commit/18be38a15d2c414fc2c260c27e5472149f35862d) et al.

Thank you.  Done.

**Comment by jmarshall** [comment]
Thanks, and similarly for the htslib one. I'm not sure how I managed to not notice you had already touched the _bamtk.c_ one :smile:; see [GNU conventions for --version](https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html) for the boring details of the conventions being followed here.

**Pull request merged**
