### PR TITLE
Vastly improve performance when many header lines

### PR DESCRIPTION
**Pull request by nathanweeks**
We observed very slow execution (i.e., running for days) of the merge phase of samtools sort while running Trinity, which uses bowtie to map reads to Inchworm contigs, and sorts the resulting BAM. Profiling the execution for a few hours with Oracle Solaris Studio Performance Analyzer revealed that the vast majority of the execution time was spent executing spent executing regexec() in pretty_header().

After running some microbenchmarks (see below), I discovered that at least the glibc regexec() implementation on Ubuntu 12.04 LTS and RHEL 6.5, as well as the BSD implementation on FreeBSD 9.4, performs very poorly when the search string is very large (as an aside, OS X does not suffer this issue; the OS X regexec man page states "The regex implementation in Mac OS X 10.8 and later is based on a heavily modified subset of TRE (http://laurikari.net/tre/).") . The the calls to regexec() in pretty_header() use the entire set of header lines as the search string, which in the case of our Trinity run contains over 6.3 million lines (~146MB) due to the large number of Inchworm-generated contigs.

To address this issue, I replaced the use of regular expressions in pretty_header() with a few string.h functions.  systems with affected regular expression implementations, it can now complete in under a second.

In addition to running the regression tests, I performance-tested the updates using a "samtools merge" on the following two bam files (warning: ~190 MB each):

https://iastate.box.com/shared/static/reeory8xntayv15ke2ei.bam
https://iastate.box.com/shared/static/0nwiupf3xa43c5gz4y0r.bam

The updated samtools merge completed in about 1 minute 50 seconds on our Ubuntu 12.04 LTS server with AMD Opteron 6272 processors. Profiling indicated that the majority of the runtime was spent performing compression.

###Microbenchmarks

The following microbenchmark using regular expressions processed ~1100 per minute of the 6,358,111 header lines in our bam file 0000.bam (```samtools view -h 0000.bam | awk '/^[^@]/{exit}{print}' > header.txt```), so processing the entire file should take well over 3.5 days (for comparison, my OS X 10.9.5 workstation processes the entire 6,358,111 header lines in ~13 seconds):

```
// USAGE: ./a.out header.txt
#include <fcntl.h>
#include <regex.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

int main(int argc, char *argv[]) {
    const char record_type[] = "@SQ";
    struct stat buf;
    int count = 0;
    char *text_in_out; 

    FILE * header = fopen(argv[1], "r");
    fstat(fileno(header), &buf);
    text_in_out = calloc(buf.st_size, 1);
    fread(text_in_out, 1, buf.st_size, header);
    
    regex_t sq_regex;
    regmatch_t matches[1];
    if (regcomp( &sq_regex, "^@SQ.*$", REG_EXTENDED|REG_NEWLINE )) abort();
    char* sq_pointer = text_in_out;
    while (text_in_out+buf.st_size > sq_pointer && regexec( &sq_regex, sq_pointer, 1, &matches[0], 0) == 0) {
        count++;
        sq_pointer += matches[0].rm_eo + 1;
    }

    printf("count: %d\n", count);
}
```

The following version, which uses string.h functions, processes the same input file in under a half second:

```
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

int main(int argc, char *argv[]) {
    const char record_type[] = "@SQ";
    struct stat buf;
    int count = 0;
    char *text_in_out; 

    FILE * header = fopen(argv[1], "r");
    fstat(fileno(header), &buf);
    text_in_out = calloc(buf.st_size, 1);
    fread(text_in_out, 1, buf.st_size, header);

    char* record_begin_pointer, *record_end_pointer = text_in_out;
    size_t record_length, record_type_length = strlen(record_type);
    while ((record_begin_pointer = strstr(record_end_pointer, record_type))) {
        record_end_pointer = strchr(record_begin_pointer, '\n');
        if (record_begin_pointer == text_in_out || *(record_begin_pointer - 1) == '\n')
            count++;
    }

    printf("count: %d\n", count);
}
```

### CODE REVIEW

**Comment by pdblood** [comment]
I confirmed that this patch solves similar issues I was encountering with Trinity when it calls 'samtools sort'.  I hope this can be pulled into the next release of samtools, as it is likely affecting a large number of Trinity users.

**Comment by jmarshall** [comment]
Thanks for analysing this and contributing, and apologies for the delay in merging.  It was a bit untried to merge immediately before making the last release, but we should have got back to it sooner.

**Comment by SamStudio8** [comment]
See also #203 from April 2014 where performance issues with large merges had already been identified previously.

**Comment by jmarshall** [comment]
@SamStudio8:  There have been a number of _separate_ performance problems with this code, notably #203 (too many pretty_header calls), #260 (O(N<sup>2</sup>) algorithm for `@SQ` headers), this one (fails prey to tragic regexp implementation on some platforms).

**Pull request merged**
