### PR TITLE
Add flag set and unset options to view.

### PR DESCRIPTION
**Pull request by whitwham**
Add options to set and unset flags.  Along with the existing option to remove aux tags this will provide the duplicate mark clearing requested in #1358.

### CODE REVIEW

**Comment by whitwham** [comment]
Leaving this as draft as I am not convinced this is the best approach and I am putting this up for discussion.

This PR also needs documentation and test cases writing.

**Comment by whitwham** [comment]
Could do.  If we are going to have long options then making them consistent would be good.

**Comment by valeriuo** [comment]
Merged as 12520cf5e001371d2ce5507e713523b0bbac7dd5 to a7449a0472f977e7a71695245c8ec284e87fa6ee

**Comment by jmarshall** [comment]
Noticing slightly late… making them consistent with mpileup's existing options and #1442's proposed long options would mean that they should be `--add-flags`/`--remove-flags` i.e. plural. 🤔

**Comment by valeriuo** [comment]
Perhaps it can be corrected in #1442 upon rebasing.

**Comment by jmarshall** [comment]
Yep, I'll be rebasing that one this morning now that this is merged. Good idea.

**Pull request closed without merging**
